In [4]:
import pandas as pd
import numpy as np
import requests
import bs4 as bs
import urllib.request

## Extracting features of 2020 movies from Wikipedia

In [2]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2020"

In [6]:
from bs4 import BeautifulSoup
import urllib.request

# First, install lxml if you want to use it
# Uncomment and run this line if you need to install lxml
# !pip install lxml

# Alternatively, use the built-in 'html.parser' instead of 'lxml'
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2019"

req = urllib.request.Request(link, headers={"User-Agent": "Mozilla/5.0"})
source = urllib.request.urlopen(req).read()
soup = BeautifulSoup(source, "html.parser")  # Changed from "lxml" to "html.parser"

print(soup.title.text)

List of American films of 2019 - Wikipedia

In [7]:
tables = soup.find_all('table',class_='wikitable sortable')

In [8]:
len(tables)

4

In [9]:
type(tables[0])

bs4.element.Tag

In [11]:
%pip install lxml
df1 = pd.read_html(str(tables[0]))[0]
df2 = pd.read_html(str(tables[1]))[0]
df3 = pd.read_html(str(tables[2]))[0]
df4 = pd.read_html(str(tables[3]).replace("'1\"\'",'"1"'))[0] # avoided "ValueError: invalid literal for int() with base 10: '1"'

Collecting lxml
  Downloading lxml-6.0.2-cp310-cp310-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp310-cp310-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 1.0 MB/s eta 0:00:04
   ------- -------------------------------- 0.8/4.0 MB 987.4 kB/s eta 0:00:04
   ------- -------------------------------- 0.8/4.0 MB 987.4 kB/s eta 0:00:04
   ---------- ----------------------------- 1.0/4.0 MB 868.0 kB/s eta 0:00:04
   ---------- ----------------------------- 1.0/4.0 MB 868.0 kB/s eta 0:00:04
   ------------- -------------------------- 1.3/4.0 MB 780.2 kB/s eta 0:00:04
   ------------- -------------------------- 1.3/4.0 MB 780.2 kB/s eta 0:00:04
   --------------- ------------------------ 1.6/4.0 MB 762.5 kB/s eta 0:00:04
   ------------------ --------------------- 1.8/4.0 MB 811.6 kB/s eta 0:00:03
   ------------------ --------------------- 1.8/4.0 MB 811.6 kB/s eta 0:00:03
   -------------------- ------------------- 2.1/4.0 MB 772.6 kB/s eta 0:00:03
   -------------------- ------------------- 2.1/4.0 MB 772.6 kB/s eta 0:00:03
   ----------------------- ---------------- 2.4/4.0 MB 780.2 kB/s eta 0:00:03
   ----------------------- ---------------- 2.4/4.0 MB 780.2 kB/s eta 0:00:03
   -------------------------- ------------- 2.6/4.0 MB 747.6 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 747.6 kB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 732.7 kB/s eta 0:00:02
   ------------------------------- -------- 3.1/4.0 MB 747.2 kB/s eta 0:00:02
   ------------------------------- -------- 3.1/4.0 MB 747.2 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 751.1 kB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 751.1 kB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 739.4 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 743.2 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 744.7 kB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.2
Note: you may need to restart the kernel to use updated packages.

C:\Users\ASUS\AppData\Local\Temp\ipykernel_7092\2327370854.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1 = pd.read_html(str(tables[0]))[0]
C:\Users\ASUS\AppData\Local\Temp\ipykernel_7092\2327370854.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df2 = pd.read_html(str(tables[1]))[0]
C:\Users\ASUS\AppData\Local\Temp\ipykernel_7092\2327370854.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df3 = pd.read_html(str(tables[2]))[0]
C:\Users\ASUS\AppData\Local\Temp\ipykernel_7092\2327370854.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df4 = pd.read_html(str(tables[3]).replace("'1\"\'",'"1"'))[0] # avoided "ValueError: invalid literal for int() with base 10: '1"'

In [12]:
df = pd.concat([df1, df2, df3, df4], ignore_index=True)

In [13]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,J A N U A R Y,4,Escape Room,Columbia Pictures / Original Film,"Adam Robitel (director); Bragi F. Schut, Maria...",[2]
1,J A N U A R Y,4,Rust Creek,IFC Films / Lunacy Productions,Jen McGowan (director); Julie Lipson (screenpl...,[3]
2,J A N U A R Y,4,American Hangman,Hangman Justice Productions,Wilson Coneybeare (director/screenplay); Donal...,[4]
3,J A N U A R Y,11,A Dog's Way Home,Columbia Pictures,Charles Martin Smith (director); W. Bruce Came...,[5]
4,J A N U A R Y,11,The Upside,STX Entertainment,Neil Burger (director); Jon Hartmere (screenpl...,[6]
...,...,...,...,...,...,...
246,D E C E M B E R,25,Spies in Disguise,20th Century Fox Animation / Blue Sky Studios ...,"Nick Bruno, Troy Quane (directors); Brad Copel...",[133]
247,D E C E M B E R,25,Little Women,Columbia Pictures / Regency Enterprises,Greta Gerwig (director/screenplay); Saoirse Ro...,[227]
248,D E C E M B E R,25,1917,Universal Pictures / DreamWorks Pictures,Sam Mendes (director/screenplay); Krysty Wilso...,[228]
249,D E C E M B E R,25,Just Mercy,Warner Bros. Pictures / Participant,"Destin Daniel Cretton (director/screenplay), A...",[229]
250,27,Clemency,Neon,Chinonye Chukwu (director/screenplay); Alfre W...,[230],NaN

In [14]:
df_2020 = df[['Title','Cast and crew']]

In [15]:
df_2020

                 Title                                      Cast and crew
0          Escape Room  Adam Robitel (director); Bragi F. Schut, Maria...
1           Rust Creek  Jen McGowan (director); Julie Lipson (screenpl...
2     American Hangman  Wilson Coneybeare (director/screenplay); Donal...
3     A Dog's Way Home  Charles Martin Smith (director); W. Bruce Came...
4           The Upside  Neil Burger (director); Jon Hartmere (screenpl...
..                 ...                                                ...
246  Spies in Disguise  Nick Bruno, Troy Quane (directors); Brad Copel...
247       Little Women  Greta Gerwig (director/screenplay); Saoirse Ro...
248               1917  Sam Mendes (director/screenplay); Krysty Wilso...
249         Just Mercy  Destin Daniel Cretton (director/screenplay), A...
250               Neon                                              [230]

[251 rows x 2 columns]

In [16]:
!pip install tmdbv3api

Collecting tmdbv3api
  Using cached tmdbv3api-1.9.0-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: requests in d:\anaconda\envs\myenv\lib\site-packages (from tmdbv3api) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda\envs\myenv\lib\site-packages (from requests->tmdbv3api) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\envs\myenv\lib\site-packages (from requests->tmdbv3api) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda\envs\myenv\lib\site-packages (from requests->tmdbv3api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\envs\myenv\lib\site-packages (from requests->tmdbv3api) (2025.7.14)
Using cached tmdbv3api-1.9.0-py3-none-any.whl (25 kB)
Installing collected packages: tmdbv3api
Successfully installed tmdbv3api-1.9.0

In [ ]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '5fd684aa7ffec0db4567c813532b6f3e'

In [ ]:
from tmdbv3api import Movie
tmdb_movie = Movie() 
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['genres']:
          genre_str = " " 
          for i in range(0,len(data_json['genres'])):
              genres.append(data_json['genres'][i]['name'])
          return genre_str.join(genres)
      else:
          return np.NaN

In [ ]:
df_2020['genres'] = df_2020['Title'].map(lambda x: get_genre(str(x)))

In [ ]:
df_2020

In [ ]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [ ]:
df_2020['director_name'] = df_2020['Cast and crew'].map(lambda x: get_director(str(x)))

In [ ]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [ ]:
df_2020['actor_1_name'] = df_2020['Cast and crew'].map(lambda x: get_actor1(str(x)))

In [ ]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [ ]:
df_2020['actor_2_name'] = df_2020['Cast and crew'].map(lambda x: get_actor2(str(x)))

In [ ]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [ ]:
df_2020['actor_3_name'] = df_2020['Cast and crew'].map(lambda x: get_actor3(str(x)))

In [ ]:
df_2020

In [ ]:
df_2020 = df_2020.rename(columns={'Title':'movie_title'})

In [ ]:
new_df20 = df_2020.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [ ]:
new_df20

In [ ]:
new_df20['comb'] = new_df20['actor_1_name'] + ' ' + new_df20['actor_2_name'] + ' '+ new_df20['actor_3_name'] + ' '+ new_df20['director_name'] +' ' + new_df20['genres']

In [ ]:
new_df20.isna().sum()

In [ ]:
new_df20 = new_df20.dropna(how='any')

In [ ]:
new_df20.isna().sum()

In [ ]:
new_df20['movie_title'] = new_df20['movie_title'].str.lower()

In [ ]:
new_df20

In [ ]:
old_df = pd.read_csv('final_data.csv')

In [ ]:
old_df

In [ ]:
final_df = old_df.append(new_df20,ignore_index=True)

In [ ]:
final_df

In [ ]:
final_df.to_csv('main_data.csv',index=False)